# Generated by Django 5.1.6 on 2025-04-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Basic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_group", models.CharField(max_length=10)),
                (
                    "person_2011",
                    models.CharField(db_column="2011_Person", max_length=20, null=True),
                ),
                (
                    "male_2011",
                    models.CharField(db_column="2011_Male", max_length=20, null=True),
                ),
                (
                    "female_2011",
                    models.CharField(db_column="2011_Female", max_length=20, null=True),
                ),
                (
                    "person_2016",
                    models.CharField(db_column="2016_Person", max_length=20, null=True),
                ),
                ("male_2016", models.IntegerField(db_column="2016_Male", null=True)),
                (
                    "female_2016",
                    models.CharField(db_column="2016_Female", max_length=20, null=True),
                ),
                (
                    "person_2021",
                    models.CharField(db_column="2021_Person", max_length=20, null=True),
                ),
                (
                    "male_2021",
                    models.CharField(db_column="2021_Male", max_length=20, null=True),
                ),
                (
                    "female_2021",
                    models.CharField(db_column="2021_Female", max_length=20, null=True),
                ),
                (
                    "person_2026",
                    models.CharField(db_column="2026_Person", max_length=20, null=True),
                ),
                (
                    "male_2026",
                    models.CharField(db_column="2026_Male", max_length=20, null=True),
                ),
                (
                    "female_2026",
                    models.CharField(db_column="2026_Female", max_length=20, null=True),
                ),
                (
                    "person_2031",
                    models.CharField(db_column="2031_Person", max_length=20, null=True),
                ),
                ("male_2031", models.IntegerField(db_column="2031_Male", null=True)),
                (
                    "female_2031",
                    models.CharField(db_column="2031_Female", max_length=20, null=True),
                ),
                (
                    "person_2036",
                    models.CharField(db_column="2036_Person", max_length=20, null=True),
                ),
                (
                    "male_2036",
                    models.CharField(db_column="2036_Male", max_length=20, null=True),
                ),
                (
                    "female_2036",
                    models.CharField(db_column="2036_Female", max_length=20, null=True),
                ),
            ],
            options={
                "verbose_name": "Population Cohort",
                "verbose_name_plural": "Population Cohorts",
                "db_table": "population_cohort",
            },
        ),
    ]
